/*
TGJU Web Service

TGJU Web Service Documentation

API version: 1.0.0
Contact: support@persianapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tgju

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// AllCommon2Change - struct for AllCommon2Change
type AllCommon2Change struct {
	Float32 *float32
	String *string
}

// float32AsAllCommon2Change is a convenience function that returns float32 wrapped in AllCommon2Change
func Float32AsAllCommon2Change(v *float32) AllCommon2Change {
	return AllCommon2Change{
		Float32: v,
	}
}

// stringAsAllCommon2Change is a convenience function that returns string wrapped in AllCommon2Change
func StringAsAllCommon2Change(v *string) AllCommon2Change {
	return AllCommon2Change{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *AllCommon2Change) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Float32
	err = newStrictDecoder(data).Decode(&dst.Float32)
	if err == nil {
		jsonFloat32, _ := json.Marshal(dst.Float32)
		if string(jsonFloat32) == "{}" { // empty struct
			dst.Float32 = nil
		} else {
			if err = validator.Validate(dst.Float32); err != nil {
				dst.Float32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Float32 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Float32 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(AllCommon2Change)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(AllCommon2Change)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src AllCommon2Change) MarshalJSON() ([]byte, error) {
	if src.Float32 != nil {
		return json.Marshal(&src.Float32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *AllCommon2Change) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Float32 != nil {
		return obj.Float32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj AllCommon2Change) GetActualInstanceValue() (interface{}) {
	if obj.Float32 != nil {
		return *obj.Float32
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableAllCommon2Change struct {
	value *AllCommon2Change
	isSet bool
}

func (v NullableAllCommon2Change) Get() *AllCommon2Change {
	return v.value
}

func (v *NullableAllCommon2Change) Set(val *AllCommon2Change) {
	v.value = val
	v.isSet = true
}

func (v NullableAllCommon2Change) IsSet() bool {
	return v.isSet
}

func (v *NullableAllCommon2Change) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAllCommon2Change(val *AllCommon2Change) *NullableAllCommon2Change {
	return &NullableAllCommon2Change{value: val, isSet: true}
}

func (v NullableAllCommon2Change) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAllCommon2Change) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


