/*
TGJU Web Service

TGJU Web Service Documentation

API version: 1.0.0
Contact: support@persianapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tgju

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AllCommon2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AllCommon2{}

// AllCommon2 struct for AllCommon2
type AllCommon2 struct {
	Key int32 `json:"key"`
	Category string `json:"category"`
	Title string `json:"title"`
	Price string `json:"price"`
	Change AllCommon2Change `json:"change"`
	Low string `json:"low"`
	High string `json:"high"`
	CreatedAt string `json:"created_at"`
}

type _AllCommon2 AllCommon2

// NewAllCommon2 instantiates a new AllCommon2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAllCommon2(key int32, category string, title string, price string, change AllCommon2Change, low string, high string, createdAt string) *AllCommon2 {
	this := AllCommon2{}
	this.Key = key
	this.Category = category
	this.Title = title
	this.Price = price
	this.Change = change
	this.Low = low
	this.High = high
	this.CreatedAt = createdAt
	return &this
}

// NewAllCommon2WithDefaults instantiates a new AllCommon2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAllCommon2WithDefaults() *AllCommon2 {
	this := AllCommon2{}
	return &this
}

// GetKey returns the Key field value
func (o *AllCommon2) GetKey() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *AllCommon2) GetKeyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *AllCommon2) SetKey(v int32) {
	o.Key = v
}

// GetCategory returns the Category field value
func (o *AllCommon2) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *AllCommon2) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *AllCommon2) SetCategory(v string) {
	o.Category = v
}

// GetTitle returns the Title field value
func (o *AllCommon2) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *AllCommon2) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *AllCommon2) SetTitle(v string) {
	o.Title = v
}

// GetPrice returns the Price field value
func (o *AllCommon2) GetPrice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *AllCommon2) GetPriceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *AllCommon2) SetPrice(v string) {
	o.Price = v
}

// GetChange returns the Change field value
func (o *AllCommon2) GetChange() AllCommon2Change {
	if o == nil {
		var ret AllCommon2Change
		return ret
	}

	return o.Change
}

// GetChangeOk returns a tuple with the Change field value
// and a boolean to check if the value has been set.
func (o *AllCommon2) GetChangeOk() (*AllCommon2Change, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Change, true
}

// SetChange sets field value
func (o *AllCommon2) SetChange(v AllCommon2Change) {
	o.Change = v
}

// GetLow returns the Low field value
func (o *AllCommon2) GetLow() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Low
}

// GetLowOk returns a tuple with the Low field value
// and a boolean to check if the value has been set.
func (o *AllCommon2) GetLowOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Low, true
}

// SetLow sets field value
func (o *AllCommon2) SetLow(v string) {
	o.Low = v
}

// GetHigh returns the High field value
func (o *AllCommon2) GetHigh() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.High
}

// GetHighOk returns a tuple with the High field value
// and a boolean to check if the value has been set.
func (o *AllCommon2) GetHighOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.High, true
}

// SetHigh sets field value
func (o *AllCommon2) SetHigh(v string) {
	o.High = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AllCommon2) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AllCommon2) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AllCommon2) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o AllCommon2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AllCommon2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["category"] = o.Category
	toSerialize["title"] = o.Title
	toSerialize["price"] = o.Price
	toSerialize["change"] = o.Change
	toSerialize["low"] = o.Low
	toSerialize["high"] = o.High
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *AllCommon2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"category",
		"title",
		"price",
		"change",
		"low",
		"high",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAllCommon2 := _AllCommon2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAllCommon2)

	if err != nil {
		return err
	}

	*o = AllCommon2(varAllCommon2)

	return err
}

type NullableAllCommon2 struct {
	value *AllCommon2
	isSet bool
}

func (v NullableAllCommon2) Get() *AllCommon2 {
	return v.value
}

func (v *NullableAllCommon2) Set(val *AllCommon2) {
	v.value = val
	v.isSet = true
}

func (v NullableAllCommon2) IsSet() bool {
	return v.isSet
}

func (v *NullableAllCommon2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAllCommon2(val *AllCommon2) *NullableAllCommon2 {
	return &NullableAllCommon2{value: val, isSet: true}
}

func (v NullableAllCommon2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAllCommon2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


