/*
TGJU Web Service

TGJU Web Service Documentation

API version: 1.0.0
Contact: support@persianapi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tgju

import (
	"encoding/json"
)

// checks if the CommonLocalResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonLocalResponse{}

// CommonLocalResponse struct for CommonLocalResponse
type CommonLocalResponse struct {
	Result []AllCommon2 `json:"result,omitempty"`
}

// NewCommonLocalResponse instantiates a new CommonLocalResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonLocalResponse() *CommonLocalResponse {
	this := CommonLocalResponse{}
	return &this
}

// NewCommonLocalResponseWithDefaults instantiates a new CommonLocalResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonLocalResponseWithDefaults() *CommonLocalResponse {
	this := CommonLocalResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *CommonLocalResponse) GetResult() []AllCommon2 {
	if o == nil || IsNil(o.Result) {
		var ret []AllCommon2
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonLocalResponse) GetResultOk() ([]AllCommon2, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *CommonLocalResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given []AllCommon2 and assigns it to the Result field.
func (o *CommonLocalResponse) SetResult(v []AllCommon2) {
	o.Result = v
}

func (o CommonLocalResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonLocalResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableCommonLocalResponse struct {
	value *CommonLocalResponse
	isSet bool
}

func (v NullableCommonLocalResponse) Get() *CommonLocalResponse {
	return v.value
}

func (v *NullableCommonLocalResponse) Set(val *CommonLocalResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonLocalResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonLocalResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonLocalResponse(val *CommonLocalResponse) *NullableCommonLocalResponse {
	return &NullableCommonLocalResponse{value: val, isSet: true}
}

func (v NullableCommonLocalResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonLocalResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


